spring:
  application:
    name: restapi

  # pour la démo
  config:
    import: optional:classpath:secrets.yml

  security:
    user:
      name: ${app.security.username}
      password: ${app.security.password}

  ai:
    ollama:
      init:
        pull-model-strategy: never
      chat:
        options:
          model: tinyllama
springdoc:
  api-docs:
    path: /api-docs
