spring.application.name=restapi
spring.ai.ollama.init.pull-model-strategy=never
spring.ai.ollama.chat.options.model=tinyllama
springdoc.api-docs.path=/api-docs

# pour la démo
spring.config.import=optional:classpath:secrets.properties

spring.security.user.name=${app.security.username}
spring.security.user.password=${app.security.password}