spring:
  application:
    name: restapi

  # pour la démo
  config:
    import: optional:classpath:secrets.yml

  security:
    user:
      name: ${app.security.username:}
      password: ${app.security.password:}

  ai:
    ollama:
      init:
        pull-model-strategy: never
      chat:
        options:
          model: tinyllama
      base-url: http://myollamacontainer-resource.epdaewgdc7d2enfu.canadaeast.azurecontainer.io:11434
