spring:
  application:
    name: restapi
  ai:
    ollama:
      base-url: http://myollamacontainer-resource.epdaewgdc7d2enfu.canadaeast.azurecontainer.io:11434
      init:
        pull-model-strategy: never
      chat:
        options:
          model: tinyllama
  security:
    user:
      name: ${APP_SECURITY_USERNAME}
      password: ${APP_SECURITY_PASSWORD}