name: CI/CD for Spring Boot with Profiles

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout le code source
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Set up l'environnement JAVA
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Exécuter les tests avec le profil test
      - name: Run Tests
        run: mvn test -Dspring.profiles.active=test
        env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          TEST_OLLAMA_URL: ${{ secrets.TEST_OLLAMA_URL }}

      # 3.1. Couverture de test avec Jacoco
      - name: Upload JaCoCo Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Add Coverage PR Comment
        uses: madrapps/jacoco-report@v1.7.1 # Popular marketplace action
        if: github.event_name == 'pull_request'
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80

      # 4. Builder le projet
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 5. Deployer sur azure
      # Use the 'azure/webapps-deploy' action which supports 'publish-profile'
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sprintboot-api-chatbot-demo'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.jar
